### ISSUE TITLE
[공통] Header 회원정보 버튼

### ISSUE THREAD

**Issue by junhobaik** [junhobaik/codedu#10]
로그인 상태일때 회원 아이디 노출, 프로필이미지 노출, 클릭시 회원정보수정, 로그아웃 가능하게 될 것

### 완료조건

- [x] 1. 로그인 상태시 노출
- [x] 2. 회원 아이디, 프로필이미지로 구성
- [x] 3. 클릭 시 드롭다운 메뉴 노출

**Comment by junhobaik** [comment]
b5d1a31
완료조건 2,3

**Comment by latilt** [comment]
0fd0bf7319e52e50b6d8bd3e9bdf70bc488bbe2e
완료조건 1
