### ISSUE TITLE
[공통] 드롭다운, 회원정보의 드롭다운메뉴

### ISSUE THREAD

**Issue by junhobaik** [junhobaik/codedu#12]
회원정보 탭을 누를때 노출되는 드롭다운 메뉴, 메뉴에 회원정보수정, 로그아웃이 탭이 있다

### 완료조건

- [x] 1. 회원 정보 탭을 누를시 노출
- [x] 2. 회원정보수정, 로그아웃으로 구성
- [x] 3. 회원정보수정시 회원정보 수정 페이지로 이동
- [x] 4. 로그아웃시 세션 로그아웃 후 인덱스 페이지로 이동
- [x] 5. 드롭다운 메뉴 외부 클릭시 메뉴 사라짐

**Comment by junhobaik** [comment]
b5d1a31
완료조건 1,2,5

**Comment by latilt** [comment]
013b84ec471181da8afb7497a267fb1d2bb7f36a
완료조건 3

**Comment by latilt** [comment]
6e854f9940b5d9f3e541b9d9b015037253392c2b
완료조건 4
