### ISSUE TITLE
[공통] 로그인 모달 레이어 제출 버튼

### ISSUE THREAD

**Issue by junhobaik** [junhobaik/codedu#17]
서버에 데이터 제출, 입력받은 이메일(ID)와 비밀번호를 사용하여 로그인

### 완료조건

- [x] 1. 이메일(ID), 비밀번호 일치 여부를 DB에서 확인하여 결과 받기
- [x] 2. 일치하는 경우 유저 로그인 상태로 전환
- [x] 3. 일치하지 않는 경우 로그인 버튼 상단에 '이메일, 비밀번호가 일치하지 않습니다' 출력
- [x] 4. 로그인 성공시 메인화면으로 이동

**Comment by latilt** [comment]
38bdf437c8cfc05142a1aed69fa5a21ce124c17f
완료조건 1, 2, 4

**Comment by latilt** [comment]
9aa4b5b7ed0872346bbf56a47154e382657e2bb9
완료조건 3
