### ISSUE TITLE
[퀴즈완료화면] 레이아웃 디자인 구현

### ISSUE THREAD

**Issue by junhobaik** [junhobaik/codedu#46]
퀴즈완료화면의 레이아웃 구현

완료조건

- [x] 1. 페이지제목
- [x] 2. 나가기 버튼
- [x] 3. 경험치
- [x] 4. 정답률
- [x] 5. 메시지

**Comment by latilt** [comment]
Complete Commit : 6eeb055442084086eda6dd15bcf6a295643d5a40
