### ISSUE TITLE
[공통] 로그인 세션 관리

### ISSUE THREAD

**Issue by zeevi6** [junhobaik/codedu#66]
- [x] 로그인/로그아웃 시 세션 생성/삭제
- [x] 세션 유무에 따른 url 접근 제한
- [x] UserInfoPage에서 로그인한 유저의 이메일, 프로필사진 표시
- [x] UserInfoPage에서 유저 이메일, 프로필사진 변경 시 헤더 영역의 이메일, 프로필사진 업데이트

**Comment by junhobaik** [comment]
2c9ac1674ab5e015405aa87b1c23a336d4e81c5c
