### ISSUE TITLE
[공통] Header 로고 홈버튼

### ISSUE THREAD

**Issue by junhobaik** [junhobaik/codedu#7]
로고, 로그인 상태에선 메인으로, 비로그인상태에선 회원가입으로 이동

### 완료조건

- [x] 1. 로고는 이미지 
- [x] 2. 로그인 상태에선 메인으로, 
- [x] 3. 비로그인상태에선 인덱스화면으로 이동한다.

**Comment by junhobaik** [comment]
b5d1a31
완료조건 1

**Comment by latilt** [comment]
b374da65b54a0a2da30d12b46cae046d2bc350b2
완료조건 2,3
