### ISSUE TITLE
[공통] Header 로그인 버튼

### ISSUE THREAD

**Issue by junhobaik** [junhobaik/codedu#9]
비로그인시 노출되는 버튼으로 누르면 로그인 모달을 팝업할 것

### 완료조건

- [x] 1. 비로그인시 노출 / 로그인시 비노출
- [x] 2. 버튼 클릭시, 로그인 모달 레이어 팝업

**Comment by junhobaik** [comment]
f4dc225
완료조건 2

**Comment by latilt** [comment]
0fd0bf7319e52e50b6d8bd3e9bdf70bc488bbe2e
완료조건 1
